export {
  config,
  cacheConfig,
  stats,
  init,
  reset,
  startBackgroundRefresh,
  startPeriodicCachePrune,
  getStats,
  getDnsCacheEntries,
  registerInterceptor,
  changeLogger,
  getAddress,
  backgroundRefresh,
} from './axios-cached-dns-resolve.js'
